env:
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: "off",
  linebreak-style: ["error", "windows"]
  import/extensions: 
    - error
    - ignorePackages
    - js: always
}
